"""
This type stub file was generated by pyright.
"""

import sys
from typing import Literal, Tuple, TypeAlias
from typing_extensions import TypeAlias

"""Code in here is only used by pypdf.filters._xobj_to_image"""
if sys.version_info[: 2] >= (3, 10):
    ...
else:
    ...
mode_str_type: TypeAlias = Literal["", "1", "RGB", "2bits", "4bits", "P", "L", "RGBA", "CMYK"]
MAX_IMAGE_MODE_NESTING_DEPTH: int = ...
def bits2byte(data: bytes, size: Tuple[int, int], bits: int) -> bytes:
    ...

