"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import List, Union
from flair.embeddings import DocumentEmbeddings, TokenEmbeddings
from keybert.backend import BaseEmbedder

class FlairBackend(BaseEmbedder):
    """Flair Embedding Model.

    The Flair embedding model used for generating document and word embeddings.

    Arguments:
        embedding_model: A Flair embedding model

    Usage:

    ```python
    from keybert.backend import FlairBackend
    from flair.embeddings import WordEmbeddings, DocumentPoolEmbeddings

    # Create a Flair Embedding model
    glove_embedding = WordEmbeddings('crawl')
    document_glove_embeddings = DocumentPoolEmbeddings([glove_embedding])

    # Pass the Flair model to create a new backend
    flair_embedder = FlairBackend(document_glove_embeddings)
    ```
    """
    def __init__(self, embedding_model: Union[TokenEmbeddings, DocumentEmbeddings]) -> None:
        ...

    def embed(self, documents: List[str], verbose: bool = ...) -> np.ndarray:
        """Embed a list of n documents/words into an n-dimensional
        matrix of embeddings
        Arguments:
            documents: A list of documents or words to be embedded
            verbose: Controls the verbosity of the process
        Returns:
            Document/words embeddings with shape (n, m) with `n` documents/words
            that each have an embeddings size of `m`.
        """
        ...
