"""
This type stub file was generated by pyright.
"""

import numpy as np
from typing import List
from keybert.backend import BaseEmbedder

class USEBackend(BaseEmbedder):
    """Universal Sentence Encoder.

    USE encodes text into high-dimensional vectors that
    are used for semantic similarity in KeyBERT.

    Arguments:
        embedding_model: An USE embedding model

    Usage:

    ```python
    import tensorflow_hub
    from keybert.backend import USEBackend

    embedding_model = tensorflow_hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
    use_embedder = USEBackend(embedding_model)
    ```
    """
    def __init__(self, embedding_model) -> None:
        ...

    def embed(self, documents: List[str], verbose: bool = ...) -> np.ndarray:
        """Embed a list of n documents/words into an n-dimensional matrix of embeddings.

        Arguments:
            documents: A list of documents or words to be embedded
            verbose: Controls the verbosity of the process

        Returns:
            Document/words embeddings with shape (n, m) with `n` documents/words
            that each have an embeddings size of `m`
        """
        ...
