"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple
from sklearn.feature_extraction.text import CountVectorizer

HAS_RICH = ...
def highlight_document(doc: str, keywords: List[Tuple[str, float]], vectorizer: CountVectorizer): # -> None:
    """Highlight keywords in a document.

    Arguments:
        doc: The document for which to extract keywords/keyphrases.
        keywords: The top n keywords for a document with their respective distances
                  to the input document.
        vectorizer: The vectorizer used for tokenizing the document.

    Returns:
        highlighted_text: The document with additional tags to highlight keywords
                          according to the rich package.
    """
    class NullHighlighter(RegexHighlighter):
        """Basic highlighter."""
        ...
    
    

