"""
This type stub file was generated by pyright.
"""

class NotInstalled:
    """This object is used to notify the user that additional dependencies need to be
    installed in order to use the string matching model.
    """
    def __init__(self, tool, dep, custom_msg=...) -> None:
        ...

    def __getattr__(self, *args, **kwargs):
        ...

    def __call__(self, *args, **kwargs):
        ...
