"""
This type stub file was generated by pyright.
"""

def process_candidate_keywords(documents, candidate_keywords): # -> list[None] | list[list[Any]]:
    """Create a common format for candidate keywords."""
    ...

def retry_with_exponential_backoff(func, initial_delay: float = ..., exponential_base: float = ..., jitter: bool = ..., max_retries: int = ..., errors: tuple = ...): # -> Callable[..., Any]:
    """Retry a function with exponential backoff."""
    ...
