"""
This type stub file was generated by pyright.
"""

from abc import ABC
from ..constants import AnnotationFlag
from ..generic._data_structures import DictionaryObject

class AnnotationDictionary(DictionaryObject, ABC):
    def __init__(self) -> None:
        ...

    @property
    def flags(self) -> AnnotationFlag:
        ...

    @flags.setter
    def flags(self, value: AnnotationFlag) -> None:
        ...



NO_FLAGS = ...
