"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Tuple, Union
from ..generic._data_structures import ArrayObject, DictionaryObject
from ..generic._fit import Fit
from ..generic._rectangle import RectangleObject
from ._base import AnnotationDictionary

class Link(AnnotationDictionary):
    def __init__(self, *, rect: Union[RectangleObject, Tuple[float, float, float, float]], border: Optional[ArrayObject] = ..., url: Optional[str] = ..., target_page_index: Optional[int] = ..., fit: Fit = ..., **kwargs: Any) -> None:
        ...
    


class Popup(AnnotationDictionary):
    def __init__(self, *, rect: Union[RectangleObject, Tuple[float, float, float, float]], parent: Optional[DictionaryObject] = ..., open: bool = ..., **kwargs: Any) -> None:
        ...
    


