"""
This type stub file was generated by pyright.
"""

from typing import Union
from .._utils import StreamType
from ._data_structures import Destination

class OutlineItem(Destination):
    def write_to_stream(self, stream: StreamType, encryption_key: Union[None, str, bytes] = ...) -> None:
        ...
