"""
This type stub file was generated by pyright.
"""

from typing import Tuple, Union
from ._base import FloatObject
from ._data_structures import ArrayObject

class RectangleObject(ArrayObject):
    """
    This class is used to represent *page boxes* in pypdf.

    These boxes include:

    * :attr:`artbox <pypdf._page.PageObject.artbox>`
    * :attr:`bleedbox <pypdf._page.PageObject.bleedbox>`
    * :attr:`cropbox <pypdf._page.PageObject.cropbox>`
    * :attr:`mediabox <pypdf._page.PageObject.mediabox>`
    * :attr:`trimbox <pypdf._page.PageObject.trimbox>`
    """
    def __init__(self, arr: Union[RectangleObject, Tuple[float, float, float, float]]) -> None:
        ...

    def scale(self, sx: float, sy: float) -> RectangleObject:
        ...

    def __repr__(self) -> str:
        ...

    @property
    def left(self) -> FloatObject:
        ...

    @left.setter
    def left(self, f: float) -> None:
        ...

    @property
    def bottom(self) -> FloatObject:
        ...

    @bottom.setter
    def bottom(self, f: float) -> None:
        ...

    @property
    def right(self) -> FloatObject:
        ...

    @right.setter
    def right(self, f: float) -> None:
        ...

    @property
    def top(self) -> FloatObject:
        ...

    @top.setter
    def top(self, f: float) -> None:
        ...

    @property
    def lower_left(self) -> Tuple[float, float]:
        """
        Property to read and modify the lower left coordinate of this box
        in (x,y) form.
        """
        ...

    @lower_left.setter
    def lower_left(self, value: Tuple[float, float]) -> None:
        ...

    @property
    def lower_right(self) -> Tuple[float, float]:
        """
        Property to read and modify the lower right coordinate of this box
        in (x,y) form.
        """
        ...

    @lower_right.setter
    def lower_right(self, value: Tuple[float, float]) -> None:
        ...

    @property
    def upper_left(self) -> Tuple[float, float]:
        """
        Property to read and modify the upper left coordinate of this box
        in (x,y) form.
        """
        ...

    @upper_left.setter
    def upper_left(self, value: Tuple[float, float]) -> None:
        ...

    @property
    def upper_right(self) -> Tuple[float, float]:
        """
        Property to read and modify the upper right coordinate of this box
        in (x,y) form.
        """
        ...

    @upper_right.setter
    def upper_right(self, value: Tuple[float, float]) -> None:
        ...

    @property
    def width(self) -> float:
        ...

    @property
    def height(self) -> float:
        ...
