"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from ._base import NameObject
from ._data_structures import DictionaryObject

f_obj = ...
class ViewerPreferences(DictionaryObject):
    def __init__(self, obj: Optional[DictionaryObject] = ...) -> None:
        ...
    
    @property
    def PRINT_SCALING(self) -> NameObject:
        ...
    
    def __new__(cls: Any, value: Any = ...) -> ViewerPreferences:
        ...
    


