"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, List, Optional, Tuple, Union
from ..generic import DictionaryObject

class TextExtraction:
    """
    A class to handle PDF text extraction operations.

    This class encapsulates all the state and operations needed for extracting
    text from PDF content streams, replacing the nested functions and nonlocal
    variables in the original implementation.
    """
    def __init__(self) -> None:
        ...
    
    def initialize_extraction(self, orientations: Tuple[int, ...] = ..., visitor_text: Optional[Callable[[Any, Any, Any, Any, Any], None]] = ..., cmaps: Optional[Dict[str, Tuple[str, float, Union[str, Dict[int, str]], Dict[str, str], DictionaryObject]]] = ...) -> None:
        """Initialize the extractor with extraction parameters."""
        ...
    
    def compute_str_widths(self, str_widths: float) -> float:
        ...
    
    def process_operation(self, operator: bytes, operands: List[Any]) -> None:
        ...
    


