"""
This type stub file was generated by pyright.
"""

from ._fixed_width_page import fixed_char_width, fixed_width_page, text_show_operations, y_coordinate_groups
from ._font import Font

"""Layout mode text extraction extension for pypdf"""
__all__ = ["Font", "fixed_char_width", "fixed_width_page", "text_show_operations", "y_coordinate_groups"]
