"""
This type stub file was generated by pyright.
"""

from pypdf._crypt_providers._base import CryptBase, CryptIdentity
from pypdf._crypt_providers._cryptography import CryptAES, CryptRC4, aes_cbc_decrypt, aes_cbc_encrypt, aes_ecb_decrypt, aes_ecb_encrypt, crypt_provider, rc4_decrypt, rc4_encrypt
from pypdf._utils import Version

if Version(crypt_provider[1]) <= Version("3.0"):
    ...
__all__ = ["CryptAES", "CryptBase", "CryptIdentity", "CryptRC4", "aes_cbc_decrypt", "aes_cbc_encrypt", "aes_ecb_decrypt", "aes_ecb_encrypt", "crypt_provider", "rc4_decrypt", "rc4_encrypt"]
