"""
This type stub file was generated by pyright.
"""

class CryptBase:
    def encrypt(self, data: bytes) -> bytes:
        ...
    
    def decrypt(self, data: bytes) -> bytes:
        ...
    


class CryptIdentity(CryptBase):
    ...


