"""
This type stub file was generated by pyright.
"""

from pypdf._crypt_providers._base import CryptBase

_DEPENDENCY_ERROR_STR = ...
crypt_provider = ...
class CryptRC4(CryptBase):
    def __init__(self, key: bytes) -> None:
        ...

    def encrypt(self, data: bytes) -> bytes:
        ...

    def decrypt(self, data: bytes) -> bytes:
        ...



class CryptAES(CryptBase):
    def __init__(self, key: bytes) -> None:
        ...

    def encrypt(self, data: bytes) -> bytes:
        ...

    def decrypt(self, data: bytes) -> bytes:
        ...



def rc4_encrypt(key: bytes, data: bytes) -> bytes:
    ...

def rc4_decrypt(key: bytes, data: bytes) -> bytes:
    ...

def aes_ecb_encrypt(key: bytes, data: bytes) -> bytes:
    ...

def aes_ecb_decrypt(key: bytes, data: bytes) -> bytes:
    ...

def aes_cbc_encrypt(key: bytes, iv: bytes, data: bytes) -> bytes:
    ...

def aes_cbc_decrypt(key: bytes, iv: bytes, data: bytes) -> bytes:
    ...
